apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    run: grafana-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      run: grafana-monitoring
  template:
    metadata:
      labels:
        run: grafana-monitoring
    spec:
      containers:
      - name: grafana-container
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 400m
            memory: 500Mi
      volumes:
      - name: grafana-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    run: grafana-monitoring
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 32000

