apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /todoapp/db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-claim
spec:
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteMany
