apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"istio-ingressgateway","install.operator.istio.io/owning-resource":"unknown","install.operator.istio.io/owning-resource-namespace":"istio-system","istio":"ingressgateway","istio.io/rev":"default","operator.istio.io/component":"IngressGateways","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.11.0","release":"istio"},"name":"istio-ingressgateway","namespace":"istio-system"},"spec":{"ports":[{"name":"status-port","port":15021,"protocol":"TCP","targetPort":15021},{"name":"http2","port":80,"protocol":"TCP","targetPort":8080},{"name":"https","port":443,"protocol":"TCP","targetPort":8443},{"name":"tcp","port":31400,"protocol":"TCP","targetPort":31400},{"name":"tls","port":15443,"protocol":"TCP","targetPort":15443}],"selector":{"app":"istio-ingressgateway","istio":"ingressgateway"},"type":"LoadBalancer"}}
  creationTimestamp: "2021-08-27T16:26:50Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.11.0
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
  resourceVersion: "3679"
  uid: 1c942b8c-5532-455f-acad-ee4cc13f6b09
spec:
  clusterIP: 10.96.8.118
  clusterIPs:
  - 10.96.8.118
  externalTrafficPolicy: Cluster
  ports:
  - name: status-port
    nodePort: 31935
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 32115
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31143
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tcp
    nodePort: 31994
    port: 31400
    protocol: TCP
    targetPort: 31400
  - name: tls
    nodePort: 31593
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.78.158.74
