apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db_service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    run: {{ .Values.selector.run }}
  type: {{ .Values.db_service.type }}
  ports:
  - port: {{ .Values.db_service.port }}
    targetPort: {{ .Values.db_service.targetPort }}
