apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: task-marker-be-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: imageupdate=docker.io/tutug/task-marker-be
    argocd-image-updater.argoproj.io/imageupdate.update-strategy: latest
    # argocd-image-updater.argoproj.io/write-back-method: git

spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc

  project: default
  source:
    path: task-mark-helm-charts/backend
    repoURL: https://github.com/tutugodfrey/task-marker-deployment
    targetRevision: HEAD
    helm:
    - dev/tag.yaml
    - dev/replicas.yaml
  syncPolicy:
    automated: {}                                                                                                                                                                                                                                       
