apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: task-marker-fe-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: imageupdate=docker.io/tutug/task-marker-fe
    argocd-image-updater.argoproj.io/imageupdate.update-strategy: latest

spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc

  project: default
  source:
    path: task-mark-helm-charts/frontend
    repoURL: https://github.com/tutugodfrey/task-marker-deployment
    targetRevision: HEAD
    helm:
      valueFiles:
        - dev/tag.yaml
        - dev/replicas.yaml
  syncPolicy:
    automated: {}
                                                                                                                                                                                                                                                    
