apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
        name: task-marker-fe-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: tutug/task-marker-fe
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc

  project: default
  source:
    helm:
      valueFiles:
        - values-staging.yaml
    path: helm-chart
    repoURL: https://github.com/tutugodfrey/task-marker-fe
    targetRevision: HEAD
  syncPolicy:
    automated: {}
                                                                                                                                                                                                                                                    
